# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MatchUsingTime
                                 A QGIS plugin
 Match the time and point sequence with location information with the file with time information to generate the point at the position of the file.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-14
        copyright            : (C) 2021 by Yoichi Kayama/Aero Asahi Corp
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Yoichi Kayama/Aero Asahi Corp'
__date__ = '2021-07-14'
__copyright__ = '(C) 2021 by Yoichi Kayama/Aero Asahi Corp'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MatchUsingTime class from file MatchUsingTime.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MatchUsingTime import MatchUsingTimePlugin
    return MatchUsingTimePlugin()
