# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MatchUsingTime
                                 A QGIS plugin
 Match the time and point sequence with location information with the file with time information to generate the point at the position of the file.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-14
        copyright            : (C) 2021 by Yoichi Kayama/Aero Asahi Corp
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yoichi Kayama/Aero Asahi Corp'
__date__ = '2022-04-18'
__copyright__ = '(C) 2022 by Yoichi Kayama/Aero Asahi Corp'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import stat
import time
import datetime
import glob

from qgis.PyQt.QtCore import ( QCoreApplication,
                             QDateTime , QVariant)
                             
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterBoolean,
                       QgsWkbTypes,
                       QgsGeometry ,
                       QgsPointXY ,
                       QgsFeature ,
                       QgsFields ,
                       QgsField,
                       QgsFeatureRequest,
                       QgsProcessingParameterString,
                       QgsProcessingParameterNumber,
                        QgsProcessingParameterField,
                        QgsProcessingOutputVectorLayer,
                         QgsProcessingParameterFileDestination)
                        




class CreateLogFromGpxAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    JISA = 'JISA'
    
    TFIELD = 'TFIELD'

    OFILENAME = 'OFILENAME'

    

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Time log layer'),
                [QgsProcessing.TypeVectorPoint ]
            )
        )
        
        self.addParameter(
        QgsProcessingParameterField(
                self.TFIELD,
                'Time field',
              #  type=QgsProcessingParameterField.DateTime |QgsProcessingParameterField.String,
             # type=QgsProcessingParameterField.DateTime ,
                parentLayerParameterName=self.INPUT))
                
               
        
        self.addParameter(
        QgsProcessingParameterString(
                self.JISA,
                'time difference from UTC(hour)',  
               # behavior=QgsProcessingParameterFile.Folder,
               # fileFilter='JPEG (*.JPG)',
                defaultValue="9.0"
            )
            
        )

        #self.addParameter(
        #QgsProcessingParameterBoolean(
        #        self.MVLENGTH,
        #        'Add length of movie',  
        #       # behavior=QgsProcessingParameterFile.Folder,
               # fileFilter='JPEG (*.JPG)',
        #        defaultValue=False
        #    )

        #)
   
   
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).

        self.addOutput(
           QgsProcessingOutputVectorLayer(
        self.OUTPUT,
        self.tr('Output'),
        type = QgsProcessing.TypeVectorAnyGeometry)
        )

        """
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )
        """

        self.addParameter(
              QgsProcessingParameterFileDestination(self.OFILENAME, 
               self.tr('Output geopackage file name'), optional=False, fileFilter='GeoPackage (*.gpkg *.GPKG)'))
        


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        
        
        tgFields = self.parameterAsFields( parameters, self.TFIELD, context )   

        tgField = tgFields[0]


        sfields = source.fields()


        fields = QgsFields()


        for   fd in sfields :

             fields.append( fd )

       # fields.append(QgsField("idc" , QVariant.Int))
       # fields.append(QgsField("filename", QVariant.String))
        #fields.append(QgsField("filetime", QVariant.String))
        #fields.append(QgsField("logtime", QVariant.String))
        #

        #   出力用　GeoPackage  を作成する


        
        for  feature in source.getFeatures():

            tgTime = feature[tgField]
            
            #print(type(tgTime) )
              #   型判定
            if isinstance(tgTime, str):
                  #print( tgTime )
                  if  tgTime =='0:00:00':
                         #print("continue")
                         continue
                         
                  dt = datetime.datetime.strptime(tgTime, '%Y/%m/%d %H:%M:%S')
                  file_update_unix_time = dt.timestamp()
            else:
            
                  file_update_unix_time = tgTime.toSecsSinceEpoch()
                  dt = datetime.datetime.fromtimestamp(file_update_unix_time)




        
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, fields, QgsWkbTypes.Point, source.sourceCrs())




        
            
          #  sink.addFeature(nfeature, QgsFeatureSink.FastInsert)
          #  idc = idc + 1
            
            
            
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        #total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        
        #features = source.getFeatures()

        #for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
         #   if feedback.isCanceled():
         #       break

            # Add a feature in the sink
           # sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
        #    feedback.setProgress(int(current * total))

       
    
        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}
        

 
    
    
    

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'GPX変換'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Vector'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CreateLogFromGpxAlgorithm()
