# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MatchUsingTime
                                 A QGIS plugin
 Match the time and point sequence with location information with the file with time information to generate the point at the position of the file.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-07-14
        copyright            : (C) 2021 by Yoichi Kayama/Aero Asahi Corp
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Yoichi Kayama/Aero Asahi Corp'
__date__ = '2021-07-14'
__copyright__ = '(C) 2021 by Yoichi Kayama/Aero Asahi Corp'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import stat
import time
import datetime
import glob

from qgis.PyQt.QtCore import ( QCoreApplication,
                             QDateTime , QVariant)
                             
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterFile,
                       QgsWkbTypes,
                       QgsGeometry ,
                       QgsPointXY ,
                       QgsFeature ,
                       QgsFields ,
                       QgsField,
                       QgsProcessingParameterString,
                        QgsProcessingParameterField)
                        




class MatchUsingTimeAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    
    TFIELD = 'TFIELD'
    
    IFOLDER = 'IFOLDER'
    
    EXT = 'EXT'
    

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Time log layer'),
                [QgsProcessing.TypeVectorPoint ]
            )
        )
        
        self.addParameter(
        QgsProcessingParameterField(
                self.TFIELD,
                'Time field',
                type=QgsProcessingParameterField.DateTime |QgsProcessingParameterField.String,
                parentLayerParameterName=self.INPUT))
                
        
        self.addParameter(
        
        QgsProcessingParameterFile(
                self.IFOLDER,
                'Input folder',  
                behavior=QgsProcessingParameterFile.Folder,
               # fileFilter='JPEG (*.JPG)',
                defaultValue=None
            )
            
        )
        
        
        self.addParameter(
        QgsProcessingParameterString(
                self.EXT,
                'Input File extension',  
               # behavior=QgsProcessingParameterFile.Folder,
               # fileFilter='JPEG (*.JPG)',
                defaultValue=".JPG"
            )
            
        )
        

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )
        


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        
        
        
        
        fields = QgsFields()
        fields.append(QgsField("idc" , QVariant.Int))
        fields.append(QgsField("filename", QVariant.String))
        fields.append(QgsField("filetime", QVariant.String))
        fields.append(QgsField("logtime", QVariant.String))
        
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, fields, QgsWkbTypes.Point, source.sourceCrs())



        tgFields = self.parameterAsFields( parameters, self.TFIELD, context )
        
        fextent = self.parameterAsString( parameters, self.EXT, context )
        
        pArray =  self.createTimeList(  source, tgFields[0], feedback   )
        
        #print(pArray)
        
        nArray = sorted( pArray , key=lambda x:x["time"] )
        
        print( nArray )
        
        
        tgfolder = self.parameterAsString(parameters, self.IFOLDER, context)
        
        #  ファイル拡張子のフィルタ  再検討  大文字、小文字  MP4 とかの対応
        
        idc = 1
        
        files = glob.glob(tgfolder + "/*" + fextent )
        for file in files:
            modTimesinceEpoc = os.path.getmtime(file)
            #modificationTime = time.strftime('%Y-%m-%d %H:%M:%S', modTimesinceEpoc)
            modTimesinceEpoc = modTimesinceEpoc - ( 9.0 * 60.0 * 60.0 )
            
            dt = datetime.datetime.fromtimestamp(modTimesinceEpoc)
            motstr = dt.strftime('%Y-%m-%d %H:%M:%S')
            #print("file ==")
            # print(modTimesinceEpoc)
           
            qftime = QDateTime.fromString(motstr, '%Y-%m-%d %H:%M:%S')
            #qftime = QDateTime.fromMSecsSinceEpoch(modTimesinceEpoc)
            #print(file)
            #print(" Last Modified Time : ", qftime.toString('%Y-%m-%d %H:%M:%S') )
            
            #  search nearest time point coordinate
            np = self.getTimeNearest( modTimesinceEpoc , nArray )
            
            #   エラーの場合の対応追加
            
            #print(np)
            dt = datetime.datetime.fromtimestamp(np["time"])
            logstr = dt.strftime('%Y-%m-%d %H:%M:%S');
            #print("nearest ==")
            #print(np["time"])
            
            nfeature = QgsFeature(fields)
            
            nfeature["idc"]  = idc
            nfeature["filename"] = file
            nfeature["filetime"] = motstr
            nfeature["logtime"] = logstr
            
            pointxy = QgsPointXY(np["x"],np["y"])
            geom = QgsGeometry.fromPointXY(pointxy)
            nfeature.setGeometry(geom)
            
            sink.addFeature(nfeature, QgsFeatureSink.FastInsert)
            idc = idc + 1
            
            
            
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        #total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        
        #features = source.getFeatures()

        #for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
         #   if feedback.isCanceled():
         #       break

            # Add a feature in the sink
           # sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
        #    feedback.setProgress(int(current * total))

       
    
        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}
        

    
    def getTimeNearest(self,  modTimesinceEpoc , nArray ):
        tw = nArray[0]
        
        #   先頭ポイントと指定ファイルの時間差
        sa = abs( modTimesinceEpoc-tw["time"] )
        
        #print( modTimesinceEpoc )
    
        last_pt = tw
        
        

        for pt in nArray:
        
            #print(sa)
            #print(modTimesinceEpoc )
            #print(pt["time"])
            
           # print(pt["time"])      
            
            if  modTimesinceEpoc > pt["time"]:
            
                nsa = abs( modTimesinceEpoc-pt["time"] )
                 
                if nsa < sa :
                       sa = nsa
                       
                       
            else:
                #print("else")
                nsa = abs( modTimesinceEpoc-pt["time"] )
                
                #print( nsa )
                
               
                if nsa < sa :
                      return pt
                else:
                      return last_pt
               
               
            last_pt = pt
            

            
    
        return last_pt
    
    

    def createTimeList( self, source, tgField, feedback   ):
    
        retarray = []
        
        #print(tgField)
    
        #features = source.getFeatures()

        for  feature in source.getFeatures():
            tgTime = feature[tgField]
            
            #print(type(tgTime) )
              #   型判定
            if isinstance(tgTime, str):
                  #print( tgTime )
                  if  tgTime =='0:00:00':
                         #print("continue")
                         continue
                         
                  dt = datetime.datetime.strptime(tgTime, '%Y/%m/%d %H:%M:%S')
                  file_update_unix_time = dt.timestamp()
            else:
            
                  file_update_unix_time = tgTime.toSecsSinceEpoch()
                  dt = datetime.datetime.fromtimestamp(file_update_unix_time)
            #print(tgTime.toSecsSinceEpoch())
            #print( dt )
 
            geom = feature.geometry()
          #  print(QgsWkbTypes.displayString(geom.wkbType()))             マルチポイントとかの場合の対応が必要
            if geom.wkbType() == QgsWkbTypes.Point or geom.wkbType() == QgsWkbTypes.PointZ or geom.wkbType() == QgsWkbTypes.Point25D  :
                  #print("point ")
                  
                  ptg =  geom.asPoint();
                  
                  pt = {"time": file_update_unix_time, "x": ptg.x(), "y": ptg.y()}
                  
                  retarray.append( pt );
            
        
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break
    
        return retarray
        
    

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'MatchUsingTime'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Vector'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return MatchUsingTimeAlgorithm()
